#!/bin/bash

#/
#--------------------------------------------------------------------------
# Install All Dependencies for the Syntropy Network
#--------------------------------------------------------------------------
#
# To run the setup script just execute the follwoing commands:
# # export SYNTROPY_AGENT_TOKEN=YOUR_SYNTROPY_AGENT_TOKEN_HERE
# # export SYNTROPY_ACCESS_TOKEN=YOUR_SYNTROPY_ACCESS_TOKEN_HERE
# # export DO_API_KEY=YOUR_DO_API_KEY_HERE
# # git clone git@github.com:bobbyiliev/SyntropyNet-Minecraft /var/www/syntropynet ; cd /var/www/syntropynet ; time bash infrastructure/install
#--------------------------------------------------------------------------
#/

# SYNTROPY_API_KEY   = SYNTROPY_AGENT_TOKEN
# SYNTROPY_API_TOKEN = SYNTROPY_ACCESS_TOKEN

PHP="7.4"
MYSQL_SERVICE="MySQL"
MYSQL_PACKAGE="mysql-server"

function add_sudo_user(){
    echo  "| Add new syntropy sudo user ";
    # Create a new password and create our new syntropy user
    PASS=$(openssl rand -base64 32)
    useradd -G sudo -d /home/syntropy -p $PASS -m syntropy -s /bin/bash

    # Give the syntropy user ability to not always require password
    echo 'syntropy ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
}

function nginx_install(){
    echo  "| Installing Nginx ";

    apt update -y
    apt -y install nginx
    systemctl restart nginx
}

function mysql_install(){
    echo  "| Installing $MYSQL_SERVICE ";

    apt update
    apt install -y ${MYSQL_PACKAGE}
}

function php_install(){
    echo  "| Installing PHP $PHP and all necessary files";

    apt update
    apt install -y language-pack-en-base
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    apt install -y software-properties-common
    add-apt-repository -y ppa:ondrej/php
    apt -y update
    apt -y upgrade

    apt install -y unzip php-cli screen
    apt install -y php$PHP-cli php$PHP-common php$PHP-mysql php$PHP-gd php$PHP-mysql php$PHP-curl php$PHP-mbstring php$PHP-xml php$PHP-zip php$PHP-fpm curl git

    rm /usr/bin/php
    ln -s /usr/bin/php$PHP /usr/bin/php
}

function swap_setup(){
    CHECK_SWAP=$(swapon -s | wc -l)
    if [ $CHECK_SWAP -lt 1 ] ; then

        echo  "| Adding swap file "

        # Create a swap file
        sudo fallocate -l 1G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

        # Making the swap file permanent
        sudo cp /etc/fstab /etc/fstab.bak
        echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
    fi
}

function composer_install(){
    echo  "| Installing Composer ";
    export COMPOSER_ALLOW_SUPERUSER=1;
    curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
}

function npm_install(){
    echo  "| Installing npm"

    curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
    sudo apt-get install -y nodejs
}

function laravel_install(){

    echo  "| Install Laravel "
    password=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 14 | head -n 1)

    sudo chown -R syntropy:syntropy /var/www

    mysql -e "CREATE DATABASE wave DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
    mysql -e "CREATE USER 'wave'@'%' IDENTIFIED WITH mysql_native_password BY '$password'";
    mysql -e "GRANT ALL ON wave.* TO 'wave'@'%';"

    cd /var/www/syntropynet

    cp .env.example .env
    sed -i "s/DB_PASSWORD=/DB_PASSWORD=${password}/g" /var/www/syntropynet/.env

    sed -i "s/SYNTROPY_AGENT_TOKEN=/SYNTROPY_AGENT_TOKEN=${SYNTROPY_AGENT_TOKEN}/g" /var/www/syntropynet/.env
    sed -i "s/SYNTROPY_ACCESS_TOKEN=/SYNTROPY_ACCESS_TOKEN=${SYNTROPY_ACCESS_TOKEN}/g" /var/www/syntropynet/.env
    sed -i "s/DO_API_KEY=/DO_API_KEY=${DO_API_KEY}/g" /var/www/syntropynet/.env

    composer install

    php artisan key:generate

    php artisan migrate

    php artisan db:seed

    php artisan storage:link

}

function bungeecord_install(){
    echo  "| Install and start BungeeCord Proxy in Screen "
    apt install jq default-jre -y
    runuser -l  syntropy -c 'screen -dmS BungeeCord'
    runuser -l  syntropy -c 'screen -R BungeeCord -X stuff "cd /var/www/syntropynet/infrastructure/ ; java -Xms512M -Xmx512M -jar BungeeCord.jar^M"'
    runuser -l  syntropy -c 'mkdir /home/syntropy/.config'
}

function docker_install(){
    echo  "| Install Docker "
    apt install docker.io -y

    # Add the syntropy user to the docker group.
    usermod -aG docker syntropy
}

function start_syntropy_agent(){
    echo  "| Start the Syntropy agent in Docker "
    docker run --network="host" --restart=on-failure:10 --cap-add=NET_ADMIN   --cap-add=SYS_MODULE -v /var/run/docker.sock:/var/run/docker.sock:ro   --device /dev/net/tun:/dev/net/tun --name=syntropynet-agent   -e SYNTROPY_API_KEY=${SYNTROPY_AGENT_TOKEN}   -e SYNTROPY_NETWORK_API='docker' -d syntropynet/agent:stable
}

function start_minectraft(){
    echo  "| Start the Lobby Minecraft Docker container "
    docker run -d -it -p 25577:25565 -e TYPE=SPIGOT -e ONLINE_MODE=FALSE -e EULA=TRUE itzg/minecraft-server
}

function add_nginx_server_block(){
    echo  "| Configure the Nginx service "

echo "server {
        root /var/www/syntropynet/public;
        index index.php index.html index.htm;
        server_name _;
        location / {
                try_files \$uri \$uri/ /index.php?\$query_string;
        }
        location ~*  \.(jpg|jpeg|png|gif)\$1 {
                expires 365d;
        }
        location ~*  \.(ico|css|js)\$ {
                expires 365d;
        }
        location ~ \.php\$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }
        location ~ /\.ht {
                deny all;
        }
}" > /etc/nginx/sites-available/default

    # Set the Nginx service to run as the syntropy user
    sed -i "s/www-data/syntropy/g" /etc/nginx/nginx.conf
    sed -i "s/www-data/syntropy/g" /etc/php/7.4/fpm/pool.d/www.conf

    systemctl restart nginx
    systemctl restart php7.4-fpm.service

}

function install_syntropy_cli(){
    echo  "| Install the Syntropy CLI "
    apt install python3-pip -y
    pip install syntropycli
    python3 -m site &> /dev/null && PATH="$PATH:`python3 -m site --user-base`/bin"

    echo "Make sure to specify the SYNTROPY_AGENT_TOKEN in your .env file"
}

function create_syntropy_network(){
    echo  "| Create new BungeeCord Syntropy Network "
    export SYNTROPY_API_TOKEN=${SYNTROPY_ACCESS_TOKEN}
    export SYNTROPY_API_SERVER=https://controller-prod-server.syntropystack.com

    networks=$(syntropyctl get-networks --json | jq .[].network_name)
    if [[ $string == *"BungeeCord"* ]]; then
        echo "The BungeeCord already exists!"
    else
        syntropyctl create-network BungeeCord
    fi

    echo  "| Get the current server endpoint id "
    current_server_id=$(syntropyctl get-endpoints | grep -w $(hostname) | awk '{ print $2 }')

    echo  "| Connect the endpoint with the newtwork "
    syntropyctl manage-network-endpoints BungeeCord --add-endpoint ${current_server_id}
    syntropyctl configure-endpoints ${current_server_id} --enable-all-services

    # To configure a connection run:
    # syntropyctl create-connections BungeeCord 2742 2720
}

function install_doctl_cli(){
    echo  "| Install the doctl CLI "
    snap install doctl

    echo  "| Create SSH Key and add it to DO account "
    if [[ ! -d  /var/www/syntropynet/config/id_rsa ]] ; then
        ssh-keygen -t rsa -N '' -f /var/www/syntropynet/config/id_rsa
    fi

    doctl auth init --access-token ${DO_API_KEY}

    key_id=$(doctl compute ssh-key create $(hostname)-${RANDOM} --public-key "$(cat /var/www/syntropynet/config/id_rsa.pub)")
    DO_SSH_KEY=$(echo $key_id | awk '{print $6}')
    sed -i "s/DO_SSH_KEY=/DO_SSH_KEY=${DO_SSH_KEY}/g" /var/www/syntropynet/.env

}

function main(){

    if [[ -z ${SYNTROPY_AGENT_TOKEN} ]] ; then
        echo "Specify the Syntropy Agent Token with:"
        echo ""
        echo "export SYNTROPY_AGENT_TOKEN=YOUR_SYNTROPY_AGENT_TOKEN_HERE"
        exit 1
    fi

    if [[ -z ${SYNTROPY_ACCESS_TOKEN} ]] ; then
        echo "Specify the Syntropy Acess API Token with:"
        echo ""
        echo "export SYNTROPY_ACCESS_TOKEN=YOUR_SYNTROPY_ACCESS_TOKEN"
        exit 1
    fi

    if [[ -z ${DO_API_KEY} ]] ; then
        echo "Specify the DigitalOcean API Key with:"
        echo ""
        echo "export DO_API_KEY=YOUR_DO_API_KEY_HERE"
        exit 1
    fi

    echo "| Install All Dependencies for the Syntropy Network"

    # Call all functions
    add_sudo_user
    nginx_install
    mysql_install
    php_install
    swap_setup
    composer_install
    npm_install
    laravel_install
    bungeecord_install
    docker_install
    start_syntropy_agent
    start_minectraft
    add_nginx_server_block
    install_syntropy_cli
    create_syntropy_network
    install_doctl_cli

    sudo chown -R syntropy:syntropy /var/www

    echo  "| Happy Gaming! "
}

main
